/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * checkoutForm.java
 *
 * Created on Dec 1, 2011, 8:26:45 AM
 */
package inventorytrackingsystem;


public class checkoutForm extends javax.swing.JFrame {

  /** Creates new form checkoutForm */
  public checkoutForm() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        mainScrollPane = new javax.swing.JScrollPane();
        backgroundPanel = new javax.swing.JPanel();
        assetType_panel = new javax.swing.JPanel();
        assetType_label = new javax.swing.JLabel();
        assetType_comboBox = new javax.swing.JComboBox();
        assetTypeOther_textField = new javax.swing.JTextField();
        newAsset_panel = new javax.swing.JPanel();
        newAsset_title = new javax.swing.JLabel();
        assignedTo_label = new javax.swing.JLabel();
        assignedTo_textField = new javax.swing.JTextField();
        location_label = new javax.swing.JLabel();
        location_comboBox = new javax.swing.JComboBox();
        locationOther_textField = new javax.swing.JTextField();
        building_label = new javax.swing.JLabel();
        building_comboBox = new javax.swing.JComboBox();
        room_label = new javax.swing.JLabel();
        room_textField = new javax.swing.JTextField();
        dateAcquired_label = new javax.swing.JLabel();
        dateAcquired_textField = new javax.swing.JTextField();
        purchaseOrder_label = new javax.swing.JLabel();
        purchaseOrder_textField = new javax.swing.JTextField();
        purchasePrice_label = new javax.swing.JLabel();
        purchasePrice_textField = new javax.swing.JTextField();
        vendorName_label = new javax.swing.JLabel();
        vendorName_textField = new javax.swing.JTextField();
        grantFunds_label = new javax.swing.JLabel();
        grantFunds_comboBox = new javax.swing.JComboBox();
        grantFundsOther_textField = new javax.swing.JTextField();
        disposalAsset_panel = new javax.swing.JPanel();
        disposalAsset_title = new javax.swing.JLabel();
        disposalType_label = new javax.swing.JLabel();
        disposalType_comboBox = new javax.swing.JComboBox();
        disposalTypeOther_textField = new javax.swing.JTextField();
        disposalDate_label = new javax.swing.JLabel();
        dateAcquired_textField1 = new javax.swing.JTextField();
        transferAsset_panel = new javax.swing.JPanel();
        transferAsset_title = new javax.swing.JLabel();
        transferFromName_label = new javax.swing.JLabel();
        transferFromName_textField = new javax.swing.JTextField();
        transferFromBuilding_label = new javax.swing.JLabel();
        transferFromBuilding_comboBox = new javax.swing.JComboBox();
        transferFromRoom_label = new javax.swing.JLabel();
        transferFromRoom_textField = new javax.swing.JTextField();
        transferToName_label = new javax.swing.JLabel();
        transferToName_textField = new javax.swing.JTextField();
        transferToBuilding_label = new javax.swing.JLabel();
        transferToBuilding_comboBox = new javax.swing.JComboBox();
        transferToRoom_label = new javax.swing.JLabel();
        transferToRoom_textField = new javax.swing.JTextField();
        assetDescription_panel = new javax.swing.JPanel();
        assetDescription_title = new javax.swing.JLabel();
        assetNumber_label = new javax.swing.JLabel();
        assetNumber_textField = new javax.swing.JTextField();
        assetDescription_label = new javax.swing.JLabel();
        assetDescription_scrollPane = new javax.swing.JScrollPane();
        assetDescription_textArea = new javax.swing.JTextArea();
        assetManufacturer_label = new javax.swing.JLabel();
        assetManufacturer_textField = new javax.swing.JTextField();
        assetModelNumber_label = new javax.swing.JLabel();
        assetModelNumber_textField = new javax.swing.JTextField();
        assetSerialNumber_label = new javax.swing.JLabel();
        assetSerialNumber_textField = new javax.swing.JTextField();
        assetNotes_label = new javax.swing.JLabel();
        assetNotes_scrollPane = new javax.swing.JScrollPane();
        assetNotes_textArea = new javax.swing.JTextArea();
        assetHistory_label = new javax.swing.JLabel();
        assetHistory_scrollPane = new javax.swing.JScrollPane();
        assetHistory_textArea = new javax.swing.JTextArea();
        assetSubmission_panel = new javax.swing.JPanel();
        assetEditDate_label = new javax.swing.JLabel();
        assetEditDate_textField = new javax.swing.JTextField();
        assetEditName_label = new javax.swing.JLabel();
        assetEditName_textField = new javax.swing.JTextField();
        submitItem_button = new javax.swing.JButton();
        clearForm_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 750, 750));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setResizable(false);

        mainScrollPane.setBackground(java.awt.Color.darkGray);
        mainScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        mainScrollPane.setAutoscrolls(true);
        mainScrollPane.setMaximumSize(new java.awt.Dimension(750, 750));
        mainScrollPane.setMinimumSize(new java.awt.Dimension(750, 750));
        mainScrollPane.setPreferredSize(new java.awt.Dimension(750, 750));

        backgroundPanel.setBackground(java.awt.Color.darkGray);
        backgroundPanel.setMaximumSize(new java.awt.Dimension(750, 750));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(750, 750));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(750, 750));

        assetType_panel.setBackground(java.awt.Color.gray);
        assetType_panel.setFocusable(false);
        assetType_panel.setFont(new java.awt.Font("Tahoma", 0, 12));
        assetType_panel.setMaximumSize(new java.awt.Dimension(710, 51));
        assetType_panel.setMinimumSize(new java.awt.Dimension(710, 51));
        assetType_panel.setPreferredSize(new java.awt.Dimension(710, 51));
        assetType_panel.setRequestFocusEnabled(false);

        assetType_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetType_label.setLabelFor(assetType_comboBox);
        assetType_label.setText("Type: ");

        assetType_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New Asset", "Disposal of Asset", "Transfer of Asset (location change)", "Other" }));
        assetType_comboBox.setEditor(null);
        assetType_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        assetType_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        assetType_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        assetTypeOther_textField.setEnabled(false);
        assetTypeOther_textField.setMaximumSize(new java.awt.Dimension(266, 20));
        assetTypeOther_textField.setMinimumSize(new java.awt.Dimension(266, 20));
        assetTypeOther_textField.setPreferredSize(new java.awt.Dimension(266, 20));

        javax.swing.GroupLayout assetType_panelLayout = new javax.swing.GroupLayout(assetType_panel);
        assetType_panel.setLayout(assetType_panelLayout);
        assetType_panelLayout.setHorizontalGroup(
            assetType_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assetType_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assetType_label, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assetType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assetTypeOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        assetType_panelLayout.setVerticalGroup(
            assetType_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assetType_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(assetType_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetType_label)
                    .addComponent(assetTypeOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assetType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        newAsset_panel.setBackground(java.awt.Color.gray);
        newAsset_panel.setMaximumSize(new java.awt.Dimension(710, 104));
        newAsset_panel.setMinimumSize(new java.awt.Dimension(710, 104));
        newAsset_panel.setPreferredSize(new java.awt.Dimension(710, 104));

        newAsset_title.setFont(new java.awt.Font("Tahoma", 1, 18));
        newAsset_title.setText("New Asset");

        assignedTo_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assignedTo_label.setText("Assigned To: ");

        assignedTo_textField.setMaximumSize(new java.awt.Dimension(337, 20));
        assignedTo_textField.setMinimumSize(new java.awt.Dimension(337, 20));
        assignedTo_textField.setPreferredSize(new java.awt.Dimension(337, 20));

        location_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        location_label.setText("Location: ");

        location_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hillsboro", "Cleburne", "Burleson", "Glen Rose", "Meridian", "Other" }));
        location_comboBox.setEditor(null);
        location_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        location_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        location_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        locationOther_textField.setEnabled(false);
        locationOther_textField.setMaximumSize(new java.awt.Dimension(266, 20));
        locationOther_textField.setMinimumSize(new java.awt.Dimension(266, 20));
        locationOther_textField.setPreferredSize(new java.awt.Dimension(266, 20));

        building_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        building_label.setText("Building: ");

        building_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hillsboro: Fine Arts", "Hillsboro: Bob Bullock Gym", "Hillsboro: Maintenance", "Hillsboro: Agriculture", "Hillsboro: Athletic Training", "Hillsboro: Administration", "Hillsboro: Information Technology", "Hillsboro: Lofland Hall", "Hillsboro: Student Center", "Hillsboro: Wellness Center", "Hillsboro: Baseball Complex", "Hillsboro: Testing Center", "Hillsboro: Conference Center", "Hillsboro: Administration", "Hillsboro: Counseling", "Hillsboro: Welcome Center", "Hillsboro: Baseball Fieldhouse", "Hillsboro: Bailey Hall", "Hillsboro: Bookstore", "Hillsboro: Cafeteria", "Hillsboro: Texas Heritage Museum", "Hillsboro: Performing Arts Center", "Hillsboro: Softball Complex", "Hillsboro: Library", "Hillsboro: Dudley Hall", "Hillsboro: Frazier Hall", "Hillsboro: Student Pavillion", "Hillsboro: Instruction", "Hillsboro: Science", "Hillsboro: Faculty", "Hillsboro: Criminal Justice", "Hillsboro: Industrial Technology", "Hillsboro: Security", "Hillsboro: Cosmetology", "Hillsboro: Nursing", "Hillsboro: Rodeo Arena", "Cleburne: Technology", "Cleburne: Nursing", "Cleburne: Administration", "Cleburne: Library", "Cleburne: Student Center", "Cleburne: Bookstore", "Cleburne: Instructional", "Burleson", "Glen Rose", "Meridian" }));
        building_comboBox.setEditor(null);
        building_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        building_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        building_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        room_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        room_label.setText("Room: ");

        room_textField.setMaximumSize(new java.awt.Dimension(337, 20));
        room_textField.setMinimumSize(new java.awt.Dimension(337, 20));
        room_textField.setPreferredSize(new java.awt.Dimension(337, 20));

        dateAcquired_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        dateAcquired_label.setText("Date Acquired: ");

        dateAcquired_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        dateAcquired_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        dateAcquired_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        purchaseOrder_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        purchaseOrder_label.setText("P. O. #: ");

        purchaseOrder_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        purchaseOrder_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        purchaseOrder_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        purchasePrice_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        purchasePrice_label.setText("Purchase Price: ");

        purchasePrice_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        purchasePrice_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        purchasePrice_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        vendorName_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        vendorName_label.setText("Vendor Name: ");

        vendorName_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        vendorName_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        vendorName_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        grantFunds_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        grantFunds_label.setText("Grant Funds: ");

        grantFunds_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Perkins", "Trio", "Other" }));
        grantFunds_comboBox.setEditor(null);
        grantFunds_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        grantFunds_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        grantFunds_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        grantFundsOther_textField.setEnabled(false);
        grantFundsOther_textField.setMaximumSize(new java.awt.Dimension(266, 20));
        grantFundsOther_textField.setMinimumSize(new java.awt.Dimension(266, 20));
        grantFundsOther_textField.setPreferredSize(new java.awt.Dimension(266, 20));

        javax.swing.GroupLayout newAsset_panelLayout = new javax.swing.GroupLayout(newAsset_panel);
        newAsset_panel.setLayout(newAsset_panelLayout);
        newAsset_panelLayout.setHorizontalGroup(
            newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAsset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAsset_panelLayout.createSequentialGroup()
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(location_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(newAsset_panelLayout.createSequentialGroup()
                                    .addComponent(assignedTo_label)
                                    .addGap(18, 18, 18)
                                    .addComponent(assignedTo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(room_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(building_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(location_label)
                            .addComponent(building_label)
                            .addComponent(grantFunds_label)
                            .addGroup(newAsset_panelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(grantFunds_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newAsset_panelLayout.createSequentialGroup()
                                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newAsset_panelLayout.createSequentialGroup()
                                        .addComponent(purchasePrice_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(purchasePrice_textField, 0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newAsset_panelLayout.createSequentialGroup()
                                        .addComponent(dateAcquired_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateAcquired_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vendorName_label)
                                    .addComponent(purchaseOrder_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grantFundsOther_textField, 0, 0, Short.MAX_VALUE)
                            .addComponent(vendorName_textField, 0, 0, Short.MAX_VALUE)
                            .addComponent(purchaseOrder_textField, 0, 0, Short.MAX_VALUE)
                            .addComponent(locationOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(room_label)
                    .addComponent(newAsset_title))
                .addContainerGap())
        );

        newAsset_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateAcquired_label, purchasePrice_label});

        newAsset_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {building_label, location_label, room_label});

        newAsset_panelLayout.setVerticalGroup(
            newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAsset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newAsset_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignedTo_label)
                    .addComponent(assignedTo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAsset_panelLayout.createSequentialGroup()
                        .addComponent(locationOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseOrder_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchaseOrder_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendorName_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grantFundsOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newAsset_panelLayout.createSequentialGroup()
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(location_label)
                            .addComponent(location_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(building_label)
                            .addComponent(building_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(room_label)
                            .addComponent(room_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAsset_panelLayout.createSequentialGroup()
                                .addComponent(dateAcquired_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(purchasePrice_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purchasePrice_label)))
                            .addComponent(dateAcquired_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grantFunds_label)
                            .addComponent(grantFunds_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        newAsset_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateAcquired_label, purchaseOrder_label, purchasePrice_label, vendorName_label});

        newAsset_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {building_label, location_label, room_label});

        newAsset_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {locationOther_textField, room_textField});

        disposalAsset_panel.setBackground(java.awt.Color.gray);
        disposalAsset_panel.setMaximumSize(null);
        disposalAsset_panel.setMinimumSize(new java.awt.Dimension(710, 73));
        disposalAsset_panel.setPreferredSize(new java.awt.Dimension(710, 73));

        disposalAsset_title.setFont(new java.awt.Font("Tahoma", 1, 18));
        disposalAsset_title.setText("Disposal of Asset");

        disposalType_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        disposalType_label.setText("Disposal Type: ");

        disposalType_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hillsboro", "Cleburne", "Burleson", "Glen Rose", "Meridian", "Other" }));
        disposalType_comboBox.setEditor(null);
        disposalType_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        disposalType_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        disposalType_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        disposalTypeOther_textField.setEnabled(false);
        disposalTypeOther_textField.setMaximumSize(new java.awt.Dimension(266, 20));
        disposalTypeOther_textField.setMinimumSize(new java.awt.Dimension(266, 20));
        disposalTypeOther_textField.setPreferredSize(new java.awt.Dimension(266, 20));

        disposalDate_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        disposalDate_label.setText("Disposal Date: ");

        dateAcquired_textField1.setMaximumSize(new java.awt.Dimension(254, 20));
        dateAcquired_textField1.setMinimumSize(new java.awt.Dimension(254, 20));
        dateAcquired_textField1.setPreferredSize(new java.awt.Dimension(254, 20));

        javax.swing.GroupLayout disposalAsset_panelLayout = new javax.swing.GroupLayout(disposalAsset_panel);
        disposalAsset_panel.setLayout(disposalAsset_panelLayout);
        disposalAsset_panelLayout.setHorizontalGroup(
            disposalAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disposalAsset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(disposalAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disposalAsset_title)
                    .addGroup(disposalAsset_panelLayout.createSequentialGroup()
                        .addGroup(disposalAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, disposalAsset_panelLayout.createSequentialGroup()
                                .addComponent(disposalType_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(disposalType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, disposalAsset_panelLayout.createSequentialGroup()
                                .addComponent(disposalDate_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateAcquired_textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disposalTypeOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        disposalAsset_panelLayout.setVerticalGroup(
            disposalAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disposalAsset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(disposalAsset_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(disposalAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disposalType_label)
                    .addComponent(disposalType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disposalTypeOther_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(disposalAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disposalDate_label)
                    .addComponent(dateAcquired_textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transferAsset_panel.setBackground(java.awt.Color.gray);
        transferAsset_panel.setMaximumSize(new java.awt.Dimension(710, 423));
        transferAsset_panel.setMinimumSize(new java.awt.Dimension(710, 423));
        transferAsset_panel.setPreferredSize(new java.awt.Dimension(710, 423));

        transferAsset_title.setFont(new java.awt.Font("Tahoma", 1, 18));
        transferAsset_title.setText("Transfer of Asset");

        transferFromName_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        transferFromName_label.setText("From Name: ");

        transferFromName_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        transferFromName_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        transferFromName_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        transferFromBuilding_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        transferFromBuilding_label.setText("From Building: ");

        transferFromBuilding_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hillsboro: Fine Arts", "Hillsboro: Bob Bullock Gym", "Hillsboro: Maintenance", "Hillsboro: Agriculture", "Hillsboro: Athletic Training", "Hillsboro: Administration", "Hillsboro: Information Technology", "Hillsboro: Lofland Hall", "Hillsboro: Student Center", "Hillsboro: Wellness Center", "Hillsboro: Baseball Complex", "Hillsboro: Testing Center", "Hillsboro: Conference Center", "Hillsboro: Administration", "Hillsboro: Counseling", "Hillsboro: Welcome Center", "Hillsboro: Baseball Fieldhouse", "Hillsboro: Bailey Hall", "Hillsboro: Bookstore", "Hillsboro: Cafeteria", "Hillsboro: Texas Heritage Museum", "Hillsboro: Performing Arts Center", "Hillsboro: Softball Complex", "Hillsboro: Library", "Hillsboro: Dudley Hall", "Hillsboro: Frazier Hall", "Hillsboro: Student Pavillion", "Hillsboro: Instruction", "Hillsboro: Science", "Hillsboro: Faculty", "Hillsboro: Criminal Justice", "Hillsboro: Industrial Technology", "Hillsboro: Security", "Hillsboro: Cosmetology", "Hillsboro: Nursing", "Hillsboro: Rodeo Arena", "Cleburne: Technology", "Cleburne: Nursing", "Cleburne: Administration", "Cleburne: Library", "Cleburne: Student Center", "Cleburne: Bookstore", "Cleburne: Instructional", "Burleson", "Glen Rose", "Meridian" }));
        transferFromBuilding_comboBox.setEditor(null);
        transferFromBuilding_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        transferFromBuilding_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        transferFromBuilding_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        transferFromRoom_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        transferFromRoom_label.setText("From Room: ");

        transferFromRoom_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        transferFromRoom_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        transferFromRoom_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        transferToName_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        transferToName_label.setText("To Name: ");

        transferToName_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        transferToName_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        transferToName_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        transferToBuilding_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        transferToBuilding_label.setText("To Building: ");

        transferToBuilding_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hillsboro: Fine Arts", "Hillsboro: Bob Bullock Gym", "Hillsboro: Maintenance", "Hillsboro: Agriculture", "Hillsboro: Athletic Training", "Hillsboro: Administration", "Hillsboro: Information Technology", "Hillsboro: Lofland Hall", "Hillsboro: Student Center", "Hillsboro: Wellness Center", "Hillsboro: Baseball Complex", "Hillsboro: Testing Center", "Hillsboro: Conference Center", "Hillsboro: Administration", "Hillsboro: Counseling", "Hillsboro: Welcome Center", "Hillsboro: Baseball Fieldhouse", "Hillsboro: Bailey Hall", "Hillsboro: Bookstore", "Hillsboro: Cafeteria", "Hillsboro: Texas Heritage Museum", "Hillsboro: Performing Arts Center", "Hillsboro: Softball Complex", "Hillsboro: Library", "Hillsboro: Dudley Hall", "Hillsboro: Frazier Hall", "Hillsboro: Student Pavillion", "Hillsboro: Instruction", "Hillsboro: Science", "Hillsboro: Faculty", "Hillsboro: Criminal Justice", "Hillsboro: Industrial Technology", "Hillsboro: Security", "Hillsboro: Cosmetology", "Hillsboro: Nursing", "Hillsboro: Rodeo Arena", "Cleburne: Technology", "Cleburne: Nursing", "Cleburne: Administration", "Cleburne: Library", "Cleburne: Student Center", "Cleburne: Bookstore", "Cleburne: Instructional", "Burleson", "Glen Rose", "Meridian" }));
        transferToBuilding_comboBox.setEditor(null);
        transferToBuilding_comboBox.setMaximumSize(new java.awt.Dimension(337, 20));
        transferToBuilding_comboBox.setMinimumSize(new java.awt.Dimension(337, 20));
        transferToBuilding_comboBox.setPreferredSize(new java.awt.Dimension(337, 20));

        transferToRoom_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        transferToRoom_label.setText("To Room: ");

        transferToRoom_textField.setMaximumSize(new java.awt.Dimension(254, 20));
        transferToRoom_textField.setMinimumSize(new java.awt.Dimension(254, 20));
        transferToRoom_textField.setPreferredSize(new java.awt.Dimension(254, 20));

        javax.swing.GroupLayout transferAsset_panelLayout = new javax.swing.GroupLayout(transferAsset_panel);
        transferAsset_panel.setLayout(transferAsset_panelLayout);
        transferAsset_panelLayout.setHorizontalGroup(
            transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferAsset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transferAsset_title)
                    .addGroup(transferAsset_panelLayout.createSequentialGroup()
                        .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transferAsset_panelLayout.createSequentialGroup()
                                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transferToBuilding_label)
                                    .addComponent(transferToName_label))
                                .addGap(18, 18, 18)
                                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(transferAsset_panelLayout.createSequentialGroup()
                                        .addComponent(transferToBuilding_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(transferToRoom_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(transferToRoom_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(transferToName_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transferAsset_panelLayout.createSequentialGroup()
                                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transferFromBuilding_label)
                                    .addComponent(transferFromName_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(transferAsset_panelLayout.createSequentialGroup()
                                        .addComponent(transferFromBuilding_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(transferFromRoom_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(transferFromRoom_textField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(transferFromName_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))))
                        .addGap(364, 364, 364)))
                .addContainerGap())
        );
        transferAsset_panelLayout.setVerticalGroup(
            transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferAsset_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferAsset_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferFromName_label)
                    .addComponent(transferFromName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferFromBuilding_label)
                    .addComponent(transferFromBuilding_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferFromRoom_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferFromRoom_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(transferAsset_panelLayout.createSequentialGroup()
                        .addComponent(transferToName_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transferToBuilding_label)
                            .addComponent(transferToRoom_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transferAsset_panelLayout.createSequentialGroup()
                        .addComponent(transferToName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transferAsset_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transferToBuilding_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferToRoom_label))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assetDescription_panel.setBackground(java.awt.Color.gray);
        assetDescription_panel.setMaximumSize(new java.awt.Dimension(710, 104));
        assetDescription_panel.setMinimumSize(new java.awt.Dimension(710, 104));
        assetDescription_panel.setPreferredSize(new java.awt.Dimension(710, 104));

        assetDescription_title.setFont(new java.awt.Font("Tahoma", 1, 18));
        assetDescription_title.setText("Description of Asset");

        assetNumber_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetNumber_label.setText("HC Asset#: ");

        assetNumber_textField.setMaximumSize(new java.awt.Dimension(588, 20));
        assetNumber_textField.setMinimumSize(new java.awt.Dimension(588, 20));
        assetNumber_textField.setPreferredSize(new java.awt.Dimension(588, 20));

        assetDescription_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetDescription_label.setText("Description: ");

        assetDescription_textArea.setColumns(20);
        assetDescription_textArea.setRows(5);
        assetDescription_scrollPane.setViewportView(assetDescription_textArea);

        assetManufacturer_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetManufacturer_label.setText("Manufacturer: ");

        assetManufacturer_textField.setMaximumSize(new java.awt.Dimension(588, 20));
        assetManufacturer_textField.setMinimumSize(new java.awt.Dimension(588, 20));
        assetManufacturer_textField.setPreferredSize(new java.awt.Dimension(588, 20));

        assetModelNumber_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetModelNumber_label.setText("Model #: ");

        assetModelNumber_textField.setMaximumSize(new java.awt.Dimension(588, 20));
        assetModelNumber_textField.setMinimumSize(new java.awt.Dimension(588, 20));
        assetModelNumber_textField.setPreferredSize(new java.awt.Dimension(588, 20));

        assetSerialNumber_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetSerialNumber_label.setText("Serial #: ");

        assetSerialNumber_textField.setMaximumSize(new java.awt.Dimension(588, 20));
        assetSerialNumber_textField.setMinimumSize(new java.awt.Dimension(588, 20));
        assetSerialNumber_textField.setPreferredSize(new java.awt.Dimension(588, 20));

        assetNotes_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetNotes_label.setText("Notes: ");

        assetNotes_textArea.setColumns(20);
        assetNotes_textArea.setRows(5);
        assetNotes_scrollPane.setViewportView(assetNotes_textArea);

        assetHistory_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetHistory_label.setText("History: ");

        assetHistory_textArea.setColumns(20);
        assetHistory_textArea.setRows(5);
        assetHistory_scrollPane.setViewportView(assetHistory_textArea);

        javax.swing.GroupLayout assetDescription_panelLayout = new javax.swing.GroupLayout(assetDescription_panel);
        assetDescription_panel.setLayout(assetDescription_panelLayout);
        assetDescription_panelLayout.setHorizontalGroup(
            assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetDescription_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assetDescription_panelLayout.createSequentialGroup()
                        .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetDescription_title)
                            .addGroup(assetDescription_panelLayout.createSequentialGroup()
                                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assetNumber_label)
                                    .addComponent(assetDescription_label))
                                .addGap(18, 18, 18)
                                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assetNumber_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                                    .addComponent(assetDescription_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assetDescription_panelLayout.createSequentialGroup()
                        .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, assetDescription_panelLayout.createSequentialGroup()
                                .addComponent(assetModelNumber_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assetModelNumber_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, assetDescription_panelLayout.createSequentialGroup()
                                .addComponent(assetManufacturer_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assetManufacturer_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(assetDescription_panelLayout.createSequentialGroup()
                        .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetSerialNumber_label)
                            .addComponent(assetNotes_label)
                            .addComponent(assetHistory_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetNotes_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addComponent(assetSerialNumber_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addComponent(assetHistory_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        assetDescription_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {assetManufacturer_label, assetModelNumber_label, assetSerialNumber_label});

        assetDescription_panelLayout.setVerticalGroup(
            assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetDescription_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assetDescription_title)
                .addGap(6, 6, 6)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetNumber_label)
                    .addComponent(assetNumber_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetDescription_label)
                    .addComponent(assetDescription_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetManufacturer_label)
                    .addComponent(assetManufacturer_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetModelNumber_label)
                    .addComponent(assetModelNumber_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetSerialNumber_label)
                    .addComponent(assetSerialNumber_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetNotes_label)
                    .addComponent(assetNotes_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetDescription_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetHistory_label)
                    .addComponent(assetHistory_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assetDescription_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {assetManufacturer_label, assetModelNumber_label, assetSerialNumber_label});

        assetSubmission_panel.setBackground(java.awt.Color.gray);
        assetSubmission_panel.setMaximumSize(new java.awt.Dimension(710, 42));
        assetSubmission_panel.setMinimumSize(new java.awt.Dimension(710, 42));
        assetSubmission_panel.setPreferredSize(new java.awt.Dimension(710, 42));

        assetEditDate_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetEditDate_label.setText("Date: ");

        assetEditDate_textField.setEnabled(false);
        assetEditDate_textField.setMaximumSize(new java.awt.Dimension(588, 20));
        assetEditDate_textField.setMinimumSize(new java.awt.Dimension(588, 20));
        assetEditDate_textField.setPreferredSize(new java.awt.Dimension(588, 20));

        assetEditName_label.setFont(new java.awt.Font("Tahoma", 1, 12));
        assetEditName_label.setText("Name: ");

        assetEditName_textField.setEnabled(false);
        assetEditName_textField.setMaximumSize(new java.awt.Dimension(588, 20));
        assetEditName_textField.setMinimumSize(new java.awt.Dimension(588, 20));
        assetEditName_textField.setPreferredSize(new java.awt.Dimension(588, 20));

        submitItem_button.setText("Submit New Item");

        clearForm_button.setText("Clear Form");

        javax.swing.GroupLayout assetSubmission_panelLayout = new javax.swing.GroupLayout(assetSubmission_panel);
        assetSubmission_panel.setLayout(assetSubmission_panelLayout);
        assetSubmission_panelLayout.setHorizontalGroup(
            assetSubmission_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetSubmission_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(assetSubmission_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(assetSubmission_panelLayout.createSequentialGroup()
                        .addComponent(assetEditDate_label)
                        .addGap(60, 60, 60)
                        .addComponent(assetEditDate_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assetEditName_label))
                    .addComponent(submitItem_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(assetSubmission_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearForm_button)
                    .addComponent(assetEditName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        assetSubmission_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearForm_button, submitItem_button});

        assetSubmission_panelLayout.setVerticalGroup(
            assetSubmission_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetSubmission_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(assetSubmission_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetEditDate_label)
                    .addComponent(assetEditDate_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assetEditName_label)
                    .addComponent(assetEditName_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(assetSubmission_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearForm_button)
                    .addComponent(submitItem_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assetSubmission_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clearForm_button, submitItem_button});

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newAsset_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assetType_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferAsset_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(disposalAsset_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(372, 372, 372))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(assetSubmission_panel, javax.swing.GroupLayout.Alignment.LEADING, 0, 709, Short.MAX_VALUE)
                            .addComponent(assetDescription_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 709, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(assetType_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newAsset_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(disposalAsset_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferAsset_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assetDescription_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assetSubmission_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        mainScrollPane.setViewportView(backgroundPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(checkoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(checkoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(checkoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(checkoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new checkoutForm().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assetDescription_label;
    private javax.swing.JPanel assetDescription_panel;
    private javax.swing.JScrollPane assetDescription_scrollPane;
    private javax.swing.JTextArea assetDescription_textArea;
    private javax.swing.JLabel assetDescription_title;
    private javax.swing.JLabel assetEditDate_label;
    private javax.swing.JTextField assetEditDate_textField;
    private javax.swing.JLabel assetEditName_label;
    private javax.swing.JTextField assetEditName_textField;
    private javax.swing.JLabel assetHistory_label;
    private javax.swing.JScrollPane assetHistory_scrollPane;
    private javax.swing.JTextArea assetHistory_textArea;
    private javax.swing.JLabel assetManufacturer_label;
    private javax.swing.JTextField assetManufacturer_textField;
    private javax.swing.JLabel assetModelNumber_label;
    private javax.swing.JTextField assetModelNumber_textField;
    private javax.swing.JLabel assetNotes_label;
    private javax.swing.JScrollPane assetNotes_scrollPane;
    private javax.swing.JTextArea assetNotes_textArea;
    private javax.swing.JLabel assetNumber_label;
    private javax.swing.JTextField assetNumber_textField;
    private javax.swing.JLabel assetSerialNumber_label;
    private javax.swing.JTextField assetSerialNumber_textField;
    private javax.swing.JPanel assetSubmission_panel;
    private javax.swing.JTextField assetTypeOther_textField;
    private javax.swing.JComboBox assetType_comboBox;
    private javax.swing.JLabel assetType_label;
    private javax.swing.JPanel assetType_panel;
    private javax.swing.JLabel assignedTo_label;
    private javax.swing.JTextField assignedTo_textField;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox building_comboBox;
    private javax.swing.JLabel building_label;
    private javax.swing.JButton clearForm_button;
    private javax.swing.JLabel dateAcquired_label;
    private javax.swing.JTextField dateAcquired_textField;
    private javax.swing.JTextField dateAcquired_textField1;
    private javax.swing.JPanel disposalAsset_panel;
    private javax.swing.JLabel disposalAsset_title;
    private javax.swing.JLabel disposalDate_label;
    private javax.swing.JTextField disposalTypeOther_textField;
    private javax.swing.JComboBox disposalType_comboBox;
    private javax.swing.JLabel disposalType_label;
    private javax.swing.JTextField grantFundsOther_textField;
    private javax.swing.JComboBox grantFunds_comboBox;
    private javax.swing.JLabel grantFunds_label;
    private javax.swing.JTextField locationOther_textField;
    private javax.swing.JComboBox location_comboBox;
    private javax.swing.JLabel location_label;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JPanel newAsset_panel;
    private javax.swing.JLabel newAsset_title;
    private javax.swing.JLabel purchaseOrder_label;
    private javax.swing.JTextField purchaseOrder_textField;
    private javax.swing.JLabel purchasePrice_label;
    private javax.swing.JTextField purchasePrice_textField;
    private javax.swing.JLabel room_label;
    private javax.swing.JTextField room_textField;
    private javax.swing.JButton submitItem_button;
    private javax.swing.JPanel transferAsset_panel;
    private javax.swing.JLabel transferAsset_title;
    private javax.swing.JComboBox transferFromBuilding_comboBox;
    private javax.swing.JLabel transferFromBuilding_label;
    private javax.swing.JLabel transferFromName_label;
    private javax.swing.JTextField transferFromName_textField;
    private javax.swing.JLabel transferFromRoom_label;
    private javax.swing.JTextField transferFromRoom_textField;
    private javax.swing.JComboBox transferToBuilding_comboBox;
    private javax.swing.JLabel transferToBuilding_label;
    private javax.swing.JLabel transferToName_label;
    private javax.swing.JTextField transferToName_textField;
    private javax.swing.JLabel transferToRoom_label;
    private javax.swing.JTextField transferToRoom_textField;
    private javax.swing.JLabel vendorName_label;
    private javax.swing.JTextField vendorName_textField;
    // End of variables declaration//GEN-END:variables
}
